version: '2'
services:
    ithalalemfundo-app:
        image: ithalalemfundo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ithalalemfundo-postgresql:5432/IthalaLemfundo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ithalalemfundo-elasticsearch:9300
        ports:
            - 8080:8080
    ithalalemfundo-postgresql:
        extends:
            file: postgresql.yml
            service: ithalalemfundo-postgresql
    ithalalemfundo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ithalalemfundo-elasticsearch
